# Generated by Django 4.0.6 on 2022-07-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_personnel_pov_alter_personnel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='pov',
        ),
    ]
