# Generated by Django 4.0.6 on 2022-08-02 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_users_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('prenom', models.CharField(default='', max_length=255)),
                ('pov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pov')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('prenom', models.CharField(default='', max_length=255)),
                ('solde', models.FloatField()),
                ('ca', models.FloatField()),
                ('pov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pov')),
            ],
        ),
    ]
