# Generated by Django 4.0.6 on 2022-08-09 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_contenir_depot_operationcaissier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='active',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='pov',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pov'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='prenom',
            field=models.CharField(default='', max_length=255),
        ),
    ]
