# Generated by Django 4.0.6 on 2022-08-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pov',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='api.pov'),
            preserve_default=False,
        ),
    ]
