# Generated by Django 4.0.6 on 2022-08-31 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='fournisseur',
        ),
    ]
