# Generated by Django 4.0.6 on 2022-08-31 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_achat_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcaissier',
            name='pov',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='api.pov'),
            preserve_default=False,
        ),
    ]
